In [1]:
name = "Hacktiv8"
Age = 54
has_laptops = True
print(name, Age, has_laptops)

Hacktiv8 54 True


In [2]:
age = 1
Age = 2
aGe = 3
AGE = 4
a_g_e = 5
_age = 6
age_ = 7
_AGE_ = 8

print(age, Age, aGe, AGE, a_g_e, _age, age_, _AGE_)

1 2 3 4 5 6 7 8


In [3]:
s = 'foo'
t = 'bar'
u = 'baz'

print(s + t)

print(s + t + u)


print('Hacktiv8 ' + 'PTP')

foobar
foobarbaz
Hacktiv8 PTP


In [4]:
# Case Conversion
s = 'HackTIV8'

# Capitalize
print(s.capitalize())

# Lower
print(s.lower())

# Swapcase
print(s.swapcase())

# Title
print(s.title())

# Uppercase
print(s.upper())

Hacktiv8
hacktiv8
hACKtiv8
Hacktiv8
HACKTIV8


In [5]:
a = ['foo', 'bar', 'baz', 'qux']

In [6]:
a

['foo', 'bar', 'baz', 'qux']

In [7]:
a = ['foo', 'bar', 'baz', 'qux']

print(a)

['foo', 'bar', 'baz', 'qux']


In [8]:
a = ['foo', 'bar', 'baz', 'qux']
b = ['baz', 'qux', 'bar', 'foo']

a == b

False

In [9]:
a = ['foo', 'bar', 'baz', 'qux']
c = ['foo', 'bar', 'baz', 'qux']

In [10]:
a==c

True

In [11]:
a = [21.42, 'foobar', 3, 4, 'bark', False, 3.14159]

print(a)

[21.42, 'foobar', 3, 4, 'bark', False, 3.14159]


In [12]:
a = ['foo', 'bar', 'baz', 'qux', 'quux', 'corge']

In [13]:
print(a[0])
print(a[5])

foo
corge


In [14]:
a = ['foo', 'bar', 'baz', 'qux', 'quux', 'corge']

a[2:5]

['baz', 'qux', 'quux']

In [15]:
a[1:4]

['bar', 'baz', 'qux']

In [16]:
print(a)

print(a + ['grault', 'garply'])
print(a * 2)

['foo', 'bar', 'baz', 'qux', 'quux', 'corge']
['foo', 'bar', 'baz', 'qux', 'quux', 'corge', 'grault', 'garply']
['foo', 'bar', 'baz', 'qux', 'quux', 'corge', 'foo', 'bar', 'baz', 'qux', 'quux', 'corge']


In [17]:
print(a + ['grault', 'garply'])

['foo', 'bar', 'baz', 'qux', 'quux', 'corge', 'grault', 'garply']


In [18]:
print(a * 2)

['foo', 'bar', 'baz', 'qux', 'quux', 'corge', 'foo', 'bar', 'baz', 'qux', 'quux', 'corge']


In [19]:
# len(), min(), max()

print(a)

print(len(a))
print(min(a))
print(max(a))

['foo', 'bar', 'baz', 'qux', 'quux', 'corge']
6
bar
qux


In [20]:
a = ['foo', 'bar', 'baz', 'qux', 'quux', 'corge']

print(a)

a[2] = 10
a[-1] = 20

['foo', 'bar', 'baz', 'qux', 'quux', 'corge']


In [21]:
print(a)

['foo', 'bar', 10, 'qux', 'quux', 20]


In [22]:
del a[3]

In [23]:
print(a)

['foo', 'bar', 10, 'quux', 20]


In [24]:
a = ['foo', 'bar', 'baz', 'qux', 'quux', 'corge']

print(a[1:4])

['bar', 'baz', 'qux']


In [25]:
a[1:4] = [1.1, 2.2, 3.3, 4.4, 5.5]

print(a)

['foo', 1.1, 2.2, 3.3, 4.4, 5.5, 'quux', 'corge']


In [26]:
t = ('foo', 'bar', 'baz', 'qux', 'quux', 'corge')

print(t)

('foo', 'bar', 'baz', 'qux', 'quux', 'corge')


In [27]:
print(t[0])

print(t[-1])

foo
corge


In [28]:
(s1, s2, s3, s4) = ('foo', 'bar', 'baz', 'qux')

In [29]:
MLB_team = {
    'Colorado': 'Rockies',
    'Boston': 'Red Sox',
    'Minnesota': 'Twins',
    'Milwaukee': 'Brewers',
    'Seattle': 'Mariners'
}

In [30]:
colorado

NameError: name 'colorado' is not defined

In [31]:
print(MLB_team['Minnesota'])
print(MLB_team['Colorado'])

Twins
Rockies


In [32]:
MLB_team['Kansas City'] = 'Royals'

In [33]:
MLB_team

{'Colorado': 'Rockies',
 'Boston': 'Red Sox',
 'Minnesota': 'Twins',
 'Milwaukee': 'Brewers',
 'Seattle': 'Mariners',
 'Kansas City': 'Royals'}

In [34]:
MLB_team['Seattle'] = 'Seahawks'

In [35]:
MLB_team

{'Colorado': 'Rockies',
 'Boston': 'Red Sox',
 'Minnesota': 'Twins',
 'Milwaukee': 'Brewers',
 'Seattle': 'Seahawks',
 'Kansas City': 'Royals'}

In [36]:
del MLB_team['seattle']

KeyError: 'seattle'

In [37]:
del MLB_team['Seattle']

In [38]:
MLB_team

{'Colorado': 'Rockies',
 'Boston': 'Red Sox',
 'Minnesota': 'Twins',
 'Milwaukee': 'Brewers',
 'Kansas City': 'Royals'}

In [39]:
person = {}
type(person)

person['fname'] = 'Hack'
person['lname'] = 'PTP'
person['age'] = 51
person['spouse'] = 'Edna'
person['children'] = ['Ralph', 'Betty', 'Joey']
person['pets'] = {'dog': 'Fido', 'cat': 'Sox'}

In [40]:
person

{'fname': 'Hack',
 'lname': 'PTP',
 'age': 51,
 'spouse': 'Edna',
 'children': ['Ralph', 'Betty', 'Joey'],
 'pets': {'dog': 'Fido', 'cat': 'Sox'}}

In [41]:
print(person['fname'])
print(person['lname'])

Hack
PTP


In [42]:
print(person['children'])
print(person['children'][1])

['Ralph', 'Betty', 'Joey']
Betty


In [43]:
print(person['pets'])
print(person['pets']['cat'])

{'dog': 'Fido', 'cat': 'Sox'}
Sox


In [44]:
# Built-in Methods
d = {'a': 10, 'b': 20, 'c': 30}

# items
print(d.items())

# keys
print(d.keys())

# values
print(d.values())

dict_items([('a', 10), ('b', 20), ('c', 30)])
dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])


In [45]:
person1_age = 42
person2_age = 16
person3_age = 71

In [46]:
someone_is_of_working_age = (person1_age >= 18 and person1_age <= 65) or (person2_age >= 18 and person2_age <= 65) or (person3_age >= 18 and person3_age <= 65)
someone_is_of_working_age

True

In [47]:
someone_is_of_working_age = (
    (person1_age >= 18 and person1_age <= 65)
    or (person2_age >= 18 and person2_age <= 65)
    or (person3_age >= 18 and person3_age <= 65)
)

In [48]:
someone_is_of_working_age

True

In [49]:
x = 0
y = 5

if x < y:                            # Truthy
    print('yes')

if y < x:                            # Falsy
    print('yes')

if x:                                # Falsy
    print('yes')

if y:                                # Truthy
    print('yes')

if 'aul' in 'grault':                # Truthy
    print('yes')

if 'quux' in ['foo', 'bar', 'baz']:  # Falsy
    print('yes')

yes
yes
yes


In [50]:
if 'foo' in ['bar', 'baz', 'quz']:
    print('Expression was true')
    print('Executing statement in suite')
    print('...')
    print('done.')
    
print('after conditional')

after conditional


In [51]:
if 'foo' in ['foo', 'bar', 'baz']:
    print('outer condition is true')
    
    if 10>20:
        print('inner condition 1')
        
    print('between inner conditions')
    
    if 10<20:
        print('inner condition 2')
        
    print('end of outer condition')
print('After outer condition')

outer condition is true
between inner conditions
inner condition 2
end of outer condition
After outer condition


In [53]:
x = 20

if x > 50:
    print('(first suite)')
    print('x is small')
else:
    print('(second suite)')
    print('x is large')

(second suite)
x is large


In [54]:
hargaBuku = 20000
hargaMajalah = 5000
uang = 2000

if uang > hargaBuku:
    print("beli buku")
else:
    print("uang tidak cukup")


uang tidak cukup


In [55]:
hargaBuku = 20000
hargaMajalah = 5000
uang = 2000

if uang > hargaBuku:
    print("beli buku")
elif uang > hargaMajalah:
    print("beli majalah")
else:
    print("uang tidak cukup")

uang tidak cukup


In [56]:
name = 'Hacktiv8'
if name == 'Fred':
    print('Hello Fred')
elif name == 'Xander':
    print('Hello Xander')
elif name == 'Hacktiv8':
    print('Hello Hacktiv8')
elif name == 'Arnold':
    print('Hello Arnold')
else:
    print("I don't know who you are!")

Hello Hacktiv8


In [65]:
if 'a' in 'bar':
    print('foo')
elif 1/1:
    print("This won't happen")
elif var:
    print("This won't either")

foo


In [58]:
if'f' in 'foo': print('1'); print('2'); print('3')

1
2
3


In [59]:
if 'z' in 'foo': print('1'); print('2'); print('3')

In [60]:
x = 2

if x == 1: print('foo'); print('bar'); print('baz')
elif x == 2: print('qux'); print('quux')
else: print('corge'); print('grault')

qux
quux


In [61]:
x = 3
if x == 1: print('foo'); print('bar'); print('baz')
elif x == 2: print('qux'); print('quux')
else: print('corge'); print('grault')

corge
grault


In [62]:
x = 3
if x == 1:
    print('foo')
    print('bar')
    print('baz')
elif x == 2:
    print('qux')
    print('quux')
else:
    print('corge')
    print('grault')

corge
grault


In [66]:
raining = False
print("Let's go to the", 'beach' if not raining else 'library')

Let's go to the beach


In [67]:
raining = True
print("Let's go to the", 'beach' if not raining else 'library')

Let's go to the library


In [68]:
age = 12
s = 'teen' if age < 21 else 'adult'
s

'teen'

In [70]:
'yes' if ('qux' in ['foo', 'bar', 'baz']) else 'no'

'no'

In [71]:
n = 5
while n > 0:
    n -= 1
    print(n)

4
3
2
1
0


In [72]:
i = 1
while i < 6:
  print(i)
  i += 1

1
2
3
4
5


In [73]:
n = 5
while n > 0:
    n -= 1
    if n == 2:
        break # Break Statement
    print(n)
print('Loop ended.')

4
3
Loop ended.


In [74]:
n = 5
while n > 0:
    n -= 1
    if n == 2:
        continue
    print(n)
print('Loop ended.')

4
3
1
0
Loop ended.


In [75]:
n = 5
while n > 0:
    n -= 1
    print(n)
else:
    print('Loop done.')

4
3
2
1
0
Loop done.


In [2]:
n = 5
while n > 0:
    n -= 1
    print(n)
    if n == 2:
        break
else
    print('Loop done.')

SyntaxError: invalid syntax (<ipython-input-2-05bb7039bc49>, line 7)

In [3]:
n = 5
while n > 0:
    n -= 1
    if n == 2:
        break # Break Statement
    print(n)
print('Loop ended.')

4
3
Loop ended.


In [4]:
n = 5
while n > 0:
    n -= 1
    if n == 2:
        continue
    print(n)
print('Loop ended.')

4
3
1
0
Loop ended.


In [5]:
n = 5
while n > 0:
    n -= 1
    print(n)
else:
    print('Loop done.')

4
3
2
1
0
Loop done.


In [6]:
a = ['foo', 'bar']

while len(a):
    print(a.pop(0))
    
    b = ['baz', 'qux']
    
    while len(b):
        print('>', b.pop(0))

foo
> baz
> qux
bar
> baz
> qux


In [7]:
n = 5
while n > 0: n -= 1; print(n)

4
3
2
1
0


In [8]:
def my_function(p, l):
    "Function untuk mengitung luas"
    print(p * l)

In [9]:
my_function(2,4)

8


In [10]:
def printme( str ):
   "This prints a passed string into this function"
   print(str)
   return

In [11]:
# Function definition is here
def printme( str ):
   "This prints a passed string into this function"
   print(str)
   return;

# Now you can call printme function
printme("I'm first call to user defined function!")
printme("Again second call to the same function")

I'm first call to user defined function!
Again second call to the same function


In [12]:
# Function definition is here
def changeme( mylist ):
   "This changes a passed list into this function"
   mylist.append([1,2,3,4]);
   print("Values inside the function: ", mylist)
   return

# Now you can call changeme function
mylist = [10,20,30];
changeme( mylist );
print("Values outside the function: ", mylist)

Values inside the function:  [10, 20, 30, [1, 2, 3, 4]]
Values outside the function:  [10, 20, 30, [1, 2, 3, 4]]


In [13]:
# Function definition is here
def printme( str ):
   "This prints a passed string into this function"
   print(str)
   return;

# Now you can call printme function
printme(str = "Hacktiv8")

Hacktiv8


In [14]:
# Function definition is here
def printinfo( name, age ):
   "This prints a passed info into this function"
   print("Name: ", name)
   print("Age: ", age)
   return;

# Now you can call printinfo function
printinfo( age=4, name="a" )

Name:  a
Age:  4


In [15]:
# Function definition is here
def printinfo( name, age = 26 ):
   "This prints a passed info into this function"
   print("Name: ", name)
   print("Age: ", age)
   return;

# Now you can call printinfo function
printinfo( age=50, name="hacktiv8" )
printinfo( name="hacktiv" )

Name:  hacktiv8
Age:  50
Name:  hacktiv
Age:  26


In [16]:
# Function definition is here
def printinfo( arg1, *vartuple ):
   "This prints a variable passed arguments"
   print("Output is: ")
   print(arg1)
   for var in vartuple:
      print(var)
   return;

# Now you can call printinfo function
printinfo( 10 )
printinfo( 70, 60, 50, "a" )

Output is: 
10
Output is: 
70
60
50
a


In [21]:
# Function definition is here
sum = lambda arg1, arg2: arg1 + arg2;


    
# Now you can call sum as a function
print("Value of total : ", sum( 10, 20 ))
print("Value of total : ", sum( 20, 20 ))

Value of total :  30
Value of total :  40


In [19]:
# Function definition is here
def sum(arg1, arg2):
    # Add both the parameters and return them."
    total = arg1 + arg2
    total2 = total + arg1
    print("Inside the function : ", total)
    return total2

# Now you can call sum function
total = sum(10, 20)
print("Outside the function : ", total)

Inside the function :  30
Outside the function :  40


In [23]:
total = 0; 

def sum( arg1, arg2 ):

   total = arg1 + arg2; 
   print("Inside the function local total : ", total)
   return total;

    

sum( 10, 20 );
print("Outside the function global total : ", total)

Inside the function local total :  30
Outside the function global total :  0


In [25]:
jumlahKucing = 20

def jumlahHewan():
    jumlahAnjing = 30
    return jumlahKucing + jumlahAnjing

def jumlahKelinci():
    return jumlahKucing + jumlahKucing

jumlahHewan()


50

In [26]:
jumlahKelinci()

40

In [ ]:
# SOAL1 GANJIL GENAP

bil = int(input("Masukan Bilangan :"))

if bil % 2 == 0:
    print(" %d Merupakan Bilangan Genap" % bil)
else:
    print("%d Merupakan Bilangan Ganjil" % bil)

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [7]:
print(np.arange(4))
print(np.arange(0,10,2)) # (start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [11]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [12]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [13]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [15]:
array_example.ndim

3

In [17]:
array_example.size


24

In [18]:
array_example.shape


(3, 2, 4)

In [23]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [24]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [25]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [26]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [27]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [28]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [29]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [30]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [31]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [32]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [33]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [34]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [36]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [37]:
divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [38]:
c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


In [39]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [42]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [43]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [44]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [45]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [47]:
arr = np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [48]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [49]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [50]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [54]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [55]:
# You can sum the rows

b.sum(axis=0)

array([3, 3])

In [56]:
# You can sum the columns

b.sum(axis=1)

array([2, 4])

In [57]:
data = np.array([1, 2])
data

array([1, 2])

In [58]:
ones = np.ones(2)
ones

array([1., 1.])

In [59]:
data + ones

array([2., 3.])

In [60]:
data * data

array([1, 4])

In [61]:
data / data

array([1., 1.])

In [62]:
data * 2

array([2, 4])

In [63]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [64]:
A.sum()

4.8595784

In [65]:
A.min()

0.05093587

In [66]:
A.max()

0.82485143

In [67]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [68]:
A.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [69]:
A.std()

0.21392120766089617

In [70]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.65305362, 0.01752999],
       [0.06409664, 0.08865496],
       [0.3971063 , 0.93132261]])

In [71]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.41320639 0.08439412]
 [0.33075114 0.34497668]
 [0.12323044 0.12701643]]


In [72]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [73]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [74]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [75]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [76]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


In [77]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [78]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [79]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


In [80]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [81]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [82]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [102]:
Mulai=int(input("Mulai:"))
Selesai=int(input("Selesai:"))

c = np.arange(Mulai, Selesai)
d = c.reshape(3,9)
e = d.reshape(3,3,3)

c
d
e

Mulai:1
Selesai:28


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [103]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [104]:
d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [105]:
# input
n = int(input('banyak data :'))
start = int(input('mulai :'))
end = int(input('selesai:'))

banyak data :16
mulai :1
selesai:50


In [107]:
data = np.random.randint(start, end, n)
data

array([38, 17, 14,  1, 33,  1, 25, 37, 24, 39, 37, 38, 19, 48,  7, 38])

In [109]:
# dua dimensi
dua_dim = data.reshape(4,4)
dua_dim

array([[38, 17, 14,  1],
       [33,  1, 25, 37],
       [24, 39, 37, 38],
       [19, 48,  7, 38]])

In [110]:
# tukar posisi
dua_dim[:, ::-1]

array([[ 1, 14, 17, 38],
       [37, 25,  1, 33],
       [38, 37, 39, 24],
       [38,  7, 48, 19]])

In [116]:
# array 2 dimensi 10 x 10
x = np.ones((10, 10)) * 4
x[1:-1, 1:-1] = 0

x

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/ardhiraka/PFDS_sources/master/nbaallelo.csv')

In [4]:
len(df)

126314

In [5]:
df.shape

(126314, 23)

In [6]:
df.head()

gameorder       game_id lg_id  _iscopy  year_id  date_game  seasongame  \
0          1  194611010TRH   NBA        0     1947  11/1/1946           1   
1          1  194611010TRH   NBA        1     1947  11/1/1946           1   
2          2  194611020CHS   NBA        0     1947  11/2/1946           1   
3          2  194611020CHS   NBA        1     1947  11/2/1946           2   
4          3  194611020DTF   NBA        0     1947  11/2/1946           1   

   is_playoffs team_id  fran_id  ...  win_equiv  opp_id  opp_fran  opp_pts  \
0            0     TRH  Huskies  ...  40.294830     NYK    Knicks       68   
1            0     NYK   Knicks  ...  41.705170     TRH   Huskies       66   
2            0     CHS    Stags  ...  42.012257     NYK    Knicks       47   
3            0     NYK   Knicks  ...  40.692783     CHS     Stags       63   
4            0     DTF  Falcons  ...  38.864048     WSC  Capitols       50   

   opp_elo_i  opp_elo_n  game_location  game_result  forecast notes  
0  1300.0000  1306.7233              H            L  0.640065   NaN  
1  1300.0000  1293.2767              A            W  0.359935   NaN  
2  1306.7233  1297.0712              H            W  0.631101   NaN  
3  1300.0000  1309.6521              A            L  0.368899   NaN  
4  1300.0000  1320.3811              H            L  0.640065   NaN  

[5 rows x 23 columns]

In [7]:
pd.set_option("display.max.columns", None)

In [8]:
pd.set_option("display.precision", 2)

In [9]:
df.tail()

gameorder       game_id lg_id  _iscopy  year_id  date_game  \
126309      63155  201506110CLE   NBA        0     2015  6/11/2015   
126310      63156  201506140GSW   NBA        0     2015  6/14/2015   
126311      63156  201506140GSW   NBA        1     2015  6/14/2015   
126312      63157  201506170CLE   NBA        0     2015  6/16/2015   
126313      63157  201506170CLE   NBA        1     2015  6/16/2015   

        seasongame  is_playoffs team_id    fran_id  pts    elo_i    elo_n  \
126309         100            1     CLE  Cavaliers   82  1723.41  1704.39   
126310         102            1     GSW   Warriors  104  1809.98  1813.63   
126311         101            1     CLE  Cavaliers   91  1704.39  1700.74   
126312         102            1     CLE  Cavaliers   97  1700.74  1692.09   
126313         103            1     GSW   Warriors  105  1813.63  1822.29   

        win_equiv opp_id   opp_fran  opp_pts  opp_elo_i  opp_elo_n  \
126309      60.31    GSW   Warriors      103    1790.96    1809.98   
126310      68.01    CLE  Cavaliers       91    1704.39    1700.74   
126311      60.01    GSW   Warriors      104    1809.98    1813.63   
126312      59.29    GSW   Warriors      105    1813.63    1822.29   
126313      68.52    CLE  Cavaliers       97    1700.74    1692.09   

       game_location game_result  forecast notes  
126309             H           L      0.55   NaN  
126310             H           W      0.77   NaN  
126311             A           L      0.23   NaN  
126312             H           L      0.48   NaN  
126313             A           W      0.52   NaN

In [11]:
df.tail(2)

gameorder       game_id lg_id  _iscopy  year_id  date_game  \
126312      63157  201506170CLE   NBA        0     2015  6/16/2015   
126313      63157  201506170CLE   NBA        1     2015  6/16/2015   

        seasongame  is_playoffs team_id    fran_id  pts    elo_i    elo_n  \
126312         102            1     CLE  Cavaliers   97  1700.74  1692.09   
126313         103            1     GSW   Warriors  105  1813.63  1822.29   

        win_equiv opp_id   opp_fran  opp_pts  opp_elo_i  opp_elo_n  \
126312      59.29    GSW   Warriors      105    1813.63    1822.29   
126313      68.52    CLE  Cavaliers       97    1700.74    1692.09   

       game_location game_result  forecast notes  
126312             H           L      0.48   NaN  
126313             A           W      0.52   NaN

In [12]:
df.tail(3)

gameorder       game_id lg_id  _iscopy  year_id  date_game  \
126311      63156  201506140GSW   NBA        1     2015  6/14/2015   
126312      63157  201506170CLE   NBA        0     2015  6/16/2015   
126313      63157  201506170CLE   NBA        1     2015  6/16/2015   

        seasongame  is_playoffs team_id    fran_id  pts    elo_i    elo_n  \
126311         101            1     CLE  Cavaliers   91  1704.39  1700.74   
126312         102            1     CLE  Cavaliers   97  1700.74  1692.09   
126313         103            1     GSW   Warriors  105  1813.63  1822.29   

        win_equiv opp_id   opp_fran  opp_pts  opp_elo_i  opp_elo_n  \
126311      60.01    GSW   Warriors      104    1809.98    1813.63   
126312      59.29    GSW   Warriors      105    1813.63    1822.29   
126313      68.52    CLE  Cavaliers       97    1700.74    1692.09   

       game_location game_result  forecast notes  
126311             A           L      0.23   NaN  
126312             H           L      0.48   NaN  
126313             A           W      0.52   NaN

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126314 entries, 0 to 126313
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   gameorder      126314 non-null  int64  
 1   game_id        126314 non-null  object 
 2   lg_id          126314 non-null  object 
 3   _iscopy        126314 non-null  int64  
 4   year_id        126314 non-null  int64  
 5   date_game      126314 non-null  object 
 6   seasongame     126314 non-null  int64  
 7   is_playoffs    126314 non-null  int64  
 8   team_id        126314 non-null  object 
 9   fran_id        126314 non-null  object 
 10  pts            126314 non-null  int64  
 11  elo_i          126314 non-null  float64
 12  elo_n          126314 non-null  float64
 13  win_equiv      126314 non-null  float64
 14  opp_id         126314 non-null  object 
 15  opp_fran       126314 non-null  object 
 16  opp_pts        126314 non-null  int64  
 17  opp_elo_i      126314 non-nul

In [14]:
df.describe()

gameorder   _iscopy    year_id  seasongame  is_playoffs        pts  \
count  126314.00  126314.0  126314.00   126314.00    126314.00  126314.00   
mean    31579.00       0.5    1988.20       43.53         0.06     102.73   
std     18231.93       0.5      17.58       25.38         0.24      14.81   
min         1.00       0.0    1947.00        1.00         0.00       0.00   
25%     15790.00       0.0    1975.00       22.00         0.00      93.00   
50%     31579.00       0.5    1990.00       43.00         0.00     103.00   
75%     47368.00       1.0    2003.00       65.00         0.00     112.00   
max     63157.00       1.0    2015.00      108.00         1.00     186.00   

           elo_i      elo_n  win_equiv    opp_pts  opp_elo_i  opp_elo_n  \
count  126314.00  126314.00  126314.00  126314.00  126314.00  126314.00   
mean     1495.24    1495.24      41.71     102.73    1495.24    1495.24   
std       112.14     112.46      10.63      14.81     112.14     112.46   
min      1091.64    1085.77      10.15       0.00    1091.64    1085.77   
25%      1417.24    1416.99      34.10      93.00    1417.24    1416.99   
50%      1500.95    1500.95      42.11     103.00    1500.95    1500.95   
75%      1576.06    1576.29      49.64     112.00    1576.06    1576.29   
max      1853.10    1853.10      71.11     186.00    1853.10    1853.10   

        forecast  
count  126314.00  
mean        0.50  
std         0.22  
min         0.02  
25%         0.33  
50%         0.50  
75%         0.67  
max         0.98

In [15]:
df["team_id"].value_counts()

BOS    5997
NYK    5769
LAL    5078
DET    4985
PHI    4533
       ... 
DTF      60
PIT      60
INJ      60
TRH      60
SDS      11
Name: team_id, Length: 104, dtype: int64

In [16]:
df["fran_id"].value_counts()

Lakers          6024
Celtics         5997
Knicks          5769
Warriors        5657
Pistons         5650
Sixers          5644
Hawks           5572
Kings           5475
Wizards         4582
Spurs           4309
Bulls           4307
Pacers          4227
Thunder         4178
Rockets         4154
Nuggets         4120
Nets            4106
Suns            4080
Bucks           4034
Trailblazers    3870
Cavaliers       3810
Clippers        3733
Jazz            3555
Mavericks       3013
Heat            2371
Pelicans        2254
Magic           2207
Timberwolves    2131
Grizzlies       1657
Raptors         1634
Hornets          894
Colonels         846
Squires          799
Spirits          777
Stars            756
Sounds           697
Baltimore        467
Floridians       440
Condors          430
Capitols         291
Olympians        282
Sails            274
Stags            260
Bombers          249
Steamrollers     168
Packers           72
Redskins          65
Rebels            63
Waterloo     

In [17]:
df.loc[df["fran_id"] == "Lakers", "team_id"].value_counts()

LAL    5078
MNL     946
Name: team_id, dtype: int64

In [19]:
df.loc[df["team_id"] == "MNL", "date_game"].min()

'1/1/1949'

In [20]:
df.loc[df["team_id"] == "MNL", "date_game"].max()

'4/9/1959'

In [21]:
df.loc[df["team_id"] == "MNL", "date_game"].agg(("min", "max"))

min    1/1/1949
max    4/9/1959
Name: date_game, dtype: object

In [22]:
df.loc[df["team_id"] == "BOS", "pts"].sum()

626484

In [23]:
revenues = pd.Series([5555, 7000, 1980])

In [24]:
revenues

0    5555
1    7000
2    1980
dtype: int64

In [25]:
revenues.values

array([5555, 7000, 1980], dtype=int64)

In [26]:
revenues.index

RangeIndex(start=0, stop=3, step=1)

In [27]:
city_revenues = pd.Series(
    [4200, 8000, 6500],
    index=["Amsterdam", "Toronto", "Tokyo"]
)
city_revenues

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

In [28]:
city_employee_count = pd.Series({"Amsterdam": 5, "Tokyo": 8})
city_employee_count

Amsterdam    5
Tokyo        8
dtype: int64

In [29]:
city_employee_count.keys()

Index(['Amsterdam', 'Tokyo'], dtype='object')

In [30]:
"Tokyo" in city_employee_count

True

In [31]:
"New York" in city_employee_count

False

In [32]:
city_data = pd.DataFrame({
    "revenue": city_revenues,
    "employee_count": city_employee_count
})

In [33]:
city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

In [34]:
city_data.index

Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object')

In [35]:
city_data.values

array([[4.2e+03, 5.0e+00],
       [6.5e+03, 8.0e+00],
       [8.0e+03,     nan]])

In [36]:
city_data.axes

[Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object'),
 Index(['revenue', 'employee_count'], dtype='object')]

In [37]:
city_data.axes[0]

Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object')

In [38]:
city_data.axes[1]

Index(['revenue', 'employee_count'], dtype='object')

In [39]:
city_data.keys()

Index(['revenue', 'employee_count'], dtype='object')

In [40]:
"Amsterdam" in city_data

False

In [41]:
"revenue" in city_data

True

In [42]:
df.index

RangeIndex(start=0, stop=126314, step=1)

In [43]:
df.axes

[RangeIndex(start=0, stop=126314, step=1),
 Index(['gameorder', 'game_id', 'lg_id', '_iscopy', 'year_id', 'date_game',
        'seasongame', 'is_playoffs', 'team_id', 'fran_id', 'pts', 'elo_i',
        'elo_n', 'win_equiv', 'opp_id', 'opp_fran', 'opp_pts', 'opp_elo_i',
        'opp_elo_n', 'game_location', 'game_result', 'forecast', 'notes'],
       dtype='object')]

In [44]:
"points" in df.keys()

False

In [45]:
"pts" in df.keys()

True

In [46]:
city_revenues

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

In [47]:
city_revenues[1]

8000

In [48]:
city_revenues[1:]

Toronto    8000
Tokyo      6500
dtype: int64

In [49]:
city_revenues["Toronto":]

Toronto    8000
Tokyo      6500
dtype: int64

In [50]:
colors = pd.Series(
    ["red", "purple", "blue", "green", "yellow"],
    index=[1, 2, 3, 5, 8]
)

In [51]:
colors

1       red
2    purple
3      blue
5     green
8    yellow
dtype: object

In [53]:
colors.loc[1]

'red'

In [54]:
colors.iloc[0]

'red'

In [55]:
colors.loc[3:8]

3      blue
5     green
8    yellow
dtype: object

In [56]:
colors.iloc[-3]

'blue'

In [57]:
toys = pd.DataFrame([
    {"name": "ball", "shape": "sphere"},
    {"name": "Rubik's cube", "shape": "cube"}
])

In [58]:
toys["shape"]

0    sphere
1      cube
Name: shape, dtype: object

In [59]:
toys.shape

(2, 2)

In [60]:
city_data.loc["Amsterdam"]

revenue           4200.0
employee_count       5.0
Name: Amsterdam, dtype: float64

In [61]:
city_data.loc["Tokyo": "Toronto"]

revenue  employee_count
Tokyo       6500             8.0
Toronto     8000             NaN

In [62]:
city_data.iloc[1]

revenue           6500.0
employee_count       8.0
Name: Tokyo, dtype: float64

In [63]:
df.iloc[-2]

gameorder               63157
game_id          201506170CLE
lg_id                     NBA
_iscopy                     0
year_id                  2015
date_game           6/16/2015
seasongame                102
is_playoffs                 1
team_id                   CLE
fran_id             Cavaliers
pts                        97
elo_i                 1.7e+03
elo_n                 1.7e+03
win_equiv                  59
opp_id                    GSW
opp_fran             Warriors
opp_pts                   105
opp_elo_i             1.8e+03
opp_elo_n             1.8e+03
game_location               H
game_result                 L
forecast                 0.48
notes                     NaN
Name: 126312, dtype: object

In [64]:
city_data.loc["Amsterdam": "Tokyo", "revenue"]

Amsterdam    4200
Tokyo        6500
Name: revenue, dtype: int64

In [65]:
df.loc[5555:5559, ["fran_id", "opp_fran", "pts", "opp_pts"]]

fran_id  opp_fran  pts  opp_pts
5555  Pistons  Warriors   83       56
5556  Celtics    Knicks   95       74
5557   Knicks   Celtics   74       95
5558    Kings    Sixers   81       86
5559   Sixers     Kings   86       81

In [66]:
df

gameorder       game_id lg_id  _iscopy  year_id  date_game  \
0               1  194611010TRH   NBA        0     1947  11/1/1946   
1               1  194611010TRH   NBA        1     1947  11/1/1946   
2               2  194611020CHS   NBA        0     1947  11/2/1946   
3               2  194611020CHS   NBA        1     1947  11/2/1946   
4               3  194611020DTF   NBA        0     1947  11/2/1946   
...           ...           ...   ...      ...      ...        ...   
126309      63155  201506110CLE   NBA        0     2015  6/11/2015   
126310      63156  201506140GSW   NBA        0     2015  6/14/2015   
126311      63156  201506140GSW   NBA        1     2015  6/14/2015   
126312      63157  201506170CLE   NBA        0     2015  6/16/2015   
126313      63157  201506170CLE   NBA        1     2015  6/16/2015   

        seasongame  is_playoffs team_id    fran_id  pts    elo_i    elo_n  \
0                1            0     TRH    Huskies   66  1300.00  1293.28   
1                1            0     NYK     Knicks   68  1300.00  1306.72   
2                1            0     CHS      Stags   63  1300.00  1309.65   
3                2            0     NYK     Knicks   47  1306.72  1297.07   
4                1            0     DTF    Falcons   33  1300.00  1279.62   
...            ...          ...     ...        ...  ...      ...      ...   
126309         100            1     CLE  Cavaliers   82  1723.41  1704.39   
126310         102            1     GSW   Warriors  104  1809.98  1813.63   
126311         101            1     CLE  Cavaliers   91  1704.39  1700.74   
126312         102            1     CLE  Cavaliers   97  1700.74  1692.09   
126313         103            1     GSW   Warriors  105  1813.63  1822.29   

        win_equiv opp_id   opp_fran  opp_pts  opp_elo_i  opp_elo_n  \
0           40.29    NYK     Knicks       68    1300.00    1306.72   
1           41.71    TRH    Huskies       66    1300.00    1293.28   
2           42.01    NYK     Knicks       47    1306.72    1297.07   
3           40.69    CHS      Stags       63    1300.00    1309.65   
4           38.86    WSC   Capitols       50    1300.00    1320.38   
...           ...    ...        ...      ...        ...        ...   
126309      60.31    GSW   Warriors      103    1790.96    1809.98   
126310      68.01    CLE  Cavaliers       91    1704.39    1700.74   
126311      60.01    GSW   Warriors      104    1809.98    1813.63   
126312      59.29    GSW   Warriors      105    1813.63    1822.29   
126313      68.52    CLE  Cavaliers       97    1700.74    1692.09   

       game_location game_result  forecast notes  
0                  H           L      0.64   NaN  
1                  A           W      0.36   NaN  
2                  H           W      0.63   NaN  
3                  A           L      0.37   NaN  
4                  H           L      0.64   NaN  
...              ...         ...       ...   ...  
126309             H           L      0.55   NaN  
126310             H           W      0.77   NaN  
126311             A           L      0.23   NaN  
126312             H           L      0.48   NaN  
126313             A           W      0.52   NaN  

[126314 rows x 23 columns]

In [67]:
current_decade = df[df["year_id"] > 2010]

In [68]:
current_decade

gameorder       game_id lg_id  _iscopy  year_id   date_game  \
113656      56829  201010260BOS   NBA        1     2011  10/26/2010   
113657      56829  201010260BOS   NBA        0     2011  10/26/2010   
113658      56830  201010260LAL   NBA        1     2011  10/26/2010   
113659      56830  201010260LAL   NBA        0     2011  10/26/2010   
113660      56831  201010260POR   NBA        1     2011  10/26/2010   
...           ...           ...   ...      ...      ...         ...   
126309      63155  201506110CLE   NBA        0     2015   6/11/2015   
126310      63156  201506140GSW   NBA        0     2015   6/14/2015   
126311      63156  201506140GSW   NBA        1     2015   6/14/2015   
126312      63157  201506170CLE   NBA        0     2015   6/16/2015   
126313      63157  201506170CLE   NBA        1     2015   6/16/2015   

        seasongame  is_playoffs team_id    fran_id  pts    elo_i    elo_n  \
113656           1            0     MIA       Heat   80  1547.36  1543.16   
113657           1            0     BOS    Celtics   88  1625.10  1629.30   
113658           1            0     HOU    Rockets  110  1504.20  1502.60   
113659           1            0     LAL     Lakers  112  1647.60  1649.20   
113660           1            0     PHO       Suns   92  1643.02  1630.62   
...            ...          ...     ...        ...  ...      ...      ...   
126309         100            1     CLE  Cavaliers   82  1723.41  1704.39   
126310         102            1     GSW   Warriors  104  1809.98  1813.63   
126311         101            1     CLE  Cavaliers   91  1704.39  1700.74   
126312         102            1     CLE  Cavaliers   97  1700.74  1692.09   
126313         103            1     GSW   Warriors  105  1813.63  1822.29   

        win_equiv opp_id      opp_fran  opp_pts  opp_elo_i  opp_elo_n  \
113656      45.14    BOS       Celtics       88    1625.10    1629.30   
113657      53.75    MIA          Heat       80    1547.36    1543.16   
113658      40.90    LAL        Lakers      112    1647.60    1649.20   
113659      55.61    HOU       Rockets      110    1504.20    1502.60   
113660      53.88    POR  Trailblazers      106    1552.81    1565.22   
...           ...    ...           ...      ...        ...        ...   
126309      60.31    GSW      Warriors      103    1790.96    1809.98   
126310      68.01    CLE     Cavaliers       91    1704.39    1700.74   
126311      60.01    GSW      Warriors      104    1809.98    1813.63   
126312      59.29    GSW      Warriors      105    1813.63    1822.29   
126313      68.52    CLE     Cavaliers       97    1700.74    1692.09   

       game_location game_result  forecast notes  
113656             A           L      0.26   NaN  
113657             H           W      0.74   NaN  
113658             A           L      0.20   NaN  
113659             H           W      0.80   NaN  
113660             A           L      0.49   NaN  
...              ...         ...       ...   ...  
126309             H           L      0.55   NaN  
126310             H           W      0.77   NaN  
126311             A           L      0.23   NaN  
126312             H           L      0.48   NaN  
126313             A           W      0.52   NaN  

[12658 rows x 23 columns]

In [69]:
current_decade.shape

(12658, 23)

In [70]:
games_with_notes = df[df["notes"].notnull()]
games_with_notes.shape

(5424, 23)

In [71]:
ers = df[df["fran_id"].str.endswith("ers")]

In [72]:
ers.shape

(27797, 23)

In [73]:
df[
    (df["_iscopy"] == 0) &
    (df["pts"] > 100) &
    (df["opp_pts"] > 100) &
    (df["team_id"] == "BLB")
]

gameorder       game_id lg_id  _iscopy  year_id  date_game  seasongame  \
1726        864  194902260BLB   NBA        0     1949  2/26/1949          53   
4890       2446  195301100BLB   NBA        0     1953  1/10/1953          32   
4909       2455  195301140BLB   NBA        0     1953  1/14/1953          34   
5208       2605  195303110BLB   NBA        0     1953  3/11/1953          66   
5825       2913  195402220BLB   NBA        0     1954  2/22/1954          60   

      is_playoffs team_id    fran_id  pts    elo_i    elo_n  win_equiv opp_id  \
1726            0     BLB  Baltimore  114  1421.94  1419.43      38.56    MNL   
4890            0     BLB  Baltimore  126  1328.67  1356.65      25.80    BOS   
4909            0     BLB  Baltimore  104  1349.83  1346.36      24.88    MNL   
5208            0     BLB  Baltimore  107  1284.52  1282.24      19.58    NYK   
5825            0     BLB  Baltimore  110  1303.75  1301.97      20.74    BOS   

     opp_fran  opp_pts  opp_elo_i  opp_elo_n game_location game_result  \
1726   Lakers      115    1637.99    1640.49             H           L   
4890  Celtics      105    1591.14    1563.17             H           W   
4909   Lakers      112    1665.44    1668.91             H           L   
5208   Knicks      113    1649.15    1651.44             H           L   
5825  Celtics      111    1591.49    1593.27             H           L   

      forecast            notes  
1726      0.34              NaN  
4890      0.28              NaN  
4909      0.22              NaN  
5208      0.18     at Boston MA  
5825      0.25  at Worcester MA

In [74]:
df[
    (df["_iscopy"] == 0) &
    (df["team_id"].str.startswith("LA")) &
    (df["year_id"] == 1992) &
    (df["notes"].notnull())
]

gameorder       game_id lg_id  _iscopy  year_id date_game  seasongame  \
68901      34451  199205030LAC   NBA        0     1992  5/3/1992          86   
68903      34452  199205030LAL   NBA        0     1992  5/3/1992          86   

       is_playoffs team_id   fran_id  pts    elo_i   elo_n  win_equiv opp_id  \
68901            1     LAC  Clippers  115  1546.90  1556.0      47.89    UTA   
68903            1     LAL    Lakers   76  1489.65  1474.4      39.40    POR   

           opp_fran  opp_pts  opp_elo_i  opp_elo_n game_location game_result  \
68901          Jazz      107    1647.51    1638.41             H           W   
68903  Trailblazers      102    1655.12    1670.37             H           L   

       forecast                                       notes  
68901      0.50  at Anaheim, CA (Anaheim Convention Center)  
68903      0.41                            at Las Vegas, NV

In [75]:
points = df["pts"]

In [76]:
points.sum()

12976235

In [77]:
df.head(3)

gameorder       game_id lg_id  _iscopy  year_id  date_game  seasongame  \
0          1  194611010TRH   NBA        0     1947  11/1/1946           1   
1          1  194611010TRH   NBA        1     1947  11/1/1946           1   
2          2  194611020CHS   NBA        0     1947  11/2/1946           1   

   is_playoffs team_id  fran_id  pts   elo_i    elo_n  win_equiv opp_id  \
0            0     TRH  Huskies   66  1300.0  1293.28      40.29    NYK   
1            0     NYK   Knicks   68  1300.0  1306.72      41.71    TRH   
2            0     CHS    Stags   63  1300.0  1309.65      42.01    NYK   

  opp_fran  opp_pts  opp_elo_i  opp_elo_n game_location game_result  forecast  \
0   Knicks       68    1300.00    1306.72             H           L      0.64   
1  Huskies       66    1300.00    1293.28             A           W      0.36   
2   Knicks       47    1306.72    1297.07             H           W      0.63   

  notes  
0   NaN  
1   NaN  
2   NaN

In [78]:
df.groupby("fran_id", sort=False)["pts"].sum()

fran_id
Huskies           3995
Knicks          582497
Stags            20398
Falcons           3797
Capitols         22387
Celtics         626484
Steamrollers     12372
Ironmen           3674
Bombers          17793
Rebels            4474
Warriors        591224
Baltimore        37219
Jets              4482
Pistons         572758
Lakers          637444
Kings           569245
Hawks           567261
Denver            4818
Olympians        22864
Redskins          5372
Waterloo          4921
Packers           6193
Sixers          585891
Wizards         474809
Bulls           437269
Thunder         437735
Squires          91127
Stars            84940
Rockets         432504
Colonels         94435
Pacers          438288
Nuggets         445780
Spurs           453822
Spirits          85874
Sounds           75582
Floridians       49568
Nets            417809
Condors          49642
Bucks           418326
Suns            437486
Clippers        380523
Cavaliers       380416
Trailblazers    402695
Sai

In [79]:
df[
    (df["fran_id"] == "Spurs") &
    (df["year_id"] > 2010)
].groupby(["year_id", "game_result"])["game_id"].count()

year_id  game_result
2011     L              25
         W              63
2012     L              20
         W              60
2013     L              30
         W              73
2014     L              27
         W              78
2015     L              31
         W              58
Name: game_id, dtype: int64

In [80]:
df[
    (df["fran_id"] == "Warriors") &
    (df["year_id"] == 2015)
].groupby(["is_playoffs", "game_result"])["game_id"].count()

is_playoffs  game_result
0            L              15
             W              67
1            L               5
             W              16
Name: game_id, dtype: int64

In [82]:
df

gameorder       game_id lg_id  _iscopy  year_id  date_game  \
0               1  194611010TRH   NBA        0     1947  11/1/1946   
1               1  194611010TRH   NBA        1     1947  11/1/1946   
2               2  194611020CHS   NBA        0     1947  11/2/1946   
3               2  194611020CHS   NBA        1     1947  11/2/1946   
4               3  194611020DTF   NBA        0     1947  11/2/1946   
...           ...           ...   ...      ...      ...        ...   
126309      63155  201506110CLE   NBA        0     2015  6/11/2015   
126310      63156  201506140GSW   NBA        0     2015  6/14/2015   
126311      63156  201506140GSW   NBA        1     2015  6/14/2015   
126312      63157  201506170CLE   NBA        0     2015  6/16/2015   
126313      63157  201506170CLE   NBA        1     2015  6/16/2015   

        seasongame  is_playoffs team_id    fran_id  pts    elo_i    elo_n  \
0                1            0     TRH    Huskies   66  1300.00  1293.28   
1                1            0     NYK     Knicks   68  1300.00  1306.72   
2                1            0     CHS      Stags   63  1300.00  1309.65   
3                2            0     NYK     Knicks   47  1306.72  1297.07   
4                1            0     DTF    Falcons   33  1300.00  1279.62   
...            ...          ...     ...        ...  ...      ...      ...   
126309         100            1     CLE  Cavaliers   82  1723.41  1704.39   
126310         102            1     GSW   Warriors  104  1809.98  1813.63   
126311         101            1     CLE  Cavaliers   91  1704.39  1700.74   
126312         102            1     CLE  Cavaliers   97  1700.74  1692.09   
126313         103            1     GSW   Warriors  105  1813.63  1822.29   

        win_equiv opp_id   opp_fran  opp_pts  opp_elo_i  opp_elo_n  \
0           40.29    NYK     Knicks       68    1300.00    1306.72   
1           41.71    TRH    Huskies       66    1300.00    1293.28   
2           42.01    NYK     Knicks       47    1306.72    1297.07   
3           40.69    CHS      Stags       63    1300.00    1309.65   
4           38.86    WSC   Capitols       50    1300.00    1320.38   
...           ...    ...        ...      ...        ...        ...   
126309      60.31    GSW   Warriors      103    1790.96    1809.98   
126310      68.01    CLE  Cavaliers       91    1704.39    1700.74   
126311      60.01    GSW   Warriors      104    1809.98    1813.63   
126312      59.29    GSW   Warriors      105    1813.63    1822.29   
126313      68.52    CLE  Cavaliers       97    1700.74    1692.09   

       game_location game_result  forecast notes  
0                  H           L      0.64   NaN  
1                  A           W      0.36   NaN  
2                  H           W      0.63   NaN  
3                  A           L      0.37   NaN  
4                  H           L      0.64   NaN  
...              ...         ...       ...   ...  
126309             H           L      0.55   NaN  
126310             H           W      0.77   NaN  
126311             A           L      0.23   NaN  
126312             H           L      0.48   NaN  
126313             A           W      0.52   NaN  

[126314 rows x 23 columns]

In [83]:
nba = df.copy()

In [84]:
nba.shape

(126314, 23)

In [85]:
nba["difference"] = df.pts - df.opp_pts

In [86]:
nba

gameorder       game_id lg_id  _iscopy  year_id  date_game  \
0               1  194611010TRH   NBA        0     1947  11/1/1946   
1               1  194611010TRH   NBA        1     1947  11/1/1946   
2               2  194611020CHS   NBA        0     1947  11/2/1946   
3               2  194611020CHS   NBA        1     1947  11/2/1946   
4               3  194611020DTF   NBA        0     1947  11/2/1946   
...           ...           ...   ...      ...      ...        ...   
126309      63155  201506110CLE   NBA        0     2015  6/11/2015   
126310      63156  201506140GSW   NBA        0     2015  6/14/2015   
126311      63156  201506140GSW   NBA        1     2015  6/14/2015   
126312      63157  201506170CLE   NBA        0     2015  6/16/2015   
126313      63157  201506170CLE   NBA        1     2015  6/16/2015   

        seasongame  is_playoffs team_id    fran_id  pts    elo_i    elo_n  \
0                1            0     TRH    Huskies   66  1300.00  1293.28   
1                1            0     NYK     Knicks   68  1300.00  1306.72   
2                1            0     CHS      Stags   63  1300.00  1309.65   
3                2            0     NYK     Knicks   47  1306.72  1297.07   
4                1            0     DTF    Falcons   33  1300.00  1279.62   
...            ...          ...     ...        ...  ...      ...      ...   
126309         100            1     CLE  Cavaliers   82  1723.41  1704.39   
126310         102            1     GSW   Warriors  104  1809.98  1813.63   
126311         101            1     CLE  Cavaliers   91  1704.39  1700.74   
126312         102            1     CLE  Cavaliers   97  1700.74  1692.09   
126313         103            1     GSW   Warriors  105  1813.63  1822.29   

        win_equiv opp_id   opp_fran  opp_pts  opp_elo_i  opp_elo_n  \
0           40.29    NYK     Knicks       68    1300.00    1306.72   
1           41.71    TRH    Huskies       66    1300.00    1293.28   
2           42.01    NYK     Knicks       47    1306.72    1297.07   
3           40.69    CHS      Stags       63    1300.00    1309.65   
4           38.86    WSC   Capitols       50    1300.00    1320.38   
...           ...    ...        ...      ...        ...        ...   
126309      60.31    GSW   Warriors      103    1790.96    1809.98   
126310      68.01    CLE  Cavaliers       91    1704.39    1700.74   
126311      60.01    GSW   Warriors      104    1809.98    1813.63   
126312      59.29    GSW   Warriors      105    1813.63    1822.29   
126313      68.52    CLE  Cavaliers       97    1700.74    1692.09   

       game_location game_result  forecast notes  difference  
0                  H           L      0.64   NaN          -2  
1                  A           W      0.36   NaN           2  
2                  H           W      0.63   NaN          16  
3                  A           L      0.37   NaN         -16  
4                  H           L      0.64   NaN         -17  
...              ...         ...       ...   ...         ...  
126309             H           L      0.55   NaN         -21  
126310             H           W      0.77   NaN          13  
126311             A           L      0.23   NaN         -13  
126312             H           L      0.48   NaN          -8  
126313             A           W      0.52   NaN           8  

[126314 rows x 24 columns]

In [87]:
nba["difference"].max()

68

In [88]:
renamed_nba = nba.rename(
    columns={"game_result": "result", "game_location": "location"}
)

renamed_nba.head()

gameorder       game_id lg_id  _iscopy  year_id  date_game  seasongame  \
0          1  194611010TRH   NBA        0     1947  11/1/1946           1   
1          1  194611010TRH   NBA        1     1947  11/1/1946           1   
2          2  194611020CHS   NBA        0     1947  11/2/1946           1   
3          2  194611020CHS   NBA        1     1947  11/2/1946           2   
4          3  194611020DTF   NBA        0     1947  11/2/1946           1   

   is_playoffs team_id  fran_id  pts    elo_i    elo_n  win_equiv opp_id  \
0            0     TRH  Huskies   66  1300.00  1293.28      40.29    NYK   
1            0     NYK   Knicks   68  1300.00  1306.72      41.71    TRH   
2            0     CHS    Stags   63  1300.00  1309.65      42.01    NYK   
3            0     NYK   Knicks   47  1306.72  1297.07      40.69    CHS   
4            0     DTF  Falcons   33  1300.00  1279.62      38.86    WSC   

   opp_fran  opp_pts  opp_elo_i  opp_elo_n location result  forecast notes  \
0    Knicks       68    1300.00    1306.72        H      L      0.64   NaN   
1   Huskies       66    1300.00    1293.28        A      W      0.36   NaN   
2    Knicks       47    1306.72    1297.07        H      W      0.63   NaN   
3     Stags       63    1300.00    1309.65        A      L      0.37   NaN   
4  Capitols       50    1300.00    1320.38        H      L      0.64   NaN   

   difference  
0          -2  
1           2  
2          16  
3         -16  
4         -17

In [89]:
elo_columns = ["elo_i", "elo_n", "opp_elo_i", "opp_elo_n"]

In [90]:
nba.drop(elo_columns, inplace=True, axis=1)

In [91]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126314 entries, 0 to 126313
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   gameorder      126314 non-null  int64  
 1   game_id        126314 non-null  object 
 2   lg_id          126314 non-null  object 
 3   _iscopy        126314 non-null  int64  
 4   year_id        126314 non-null  int64  
 5   date_game      126314 non-null  object 
 6   seasongame     126314 non-null  int64  
 7   is_playoffs    126314 non-null  int64  
 8   team_id        126314 non-null  object 
 9   fran_id        126314 non-null  object 
 10  pts            126314 non-null  int64  
 11  win_equiv      126314 non-null  float64
 12  opp_id         126314 non-null  object 
 13  opp_fran       126314 non-null  object 
 14  opp_pts        126314 non-null  int64  
 15  game_location  126314 non-null  object 
 16  game_result    126314 non-null  object 
 17  forecast       126314 non-nul

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/ardhiraka/PFDS_sources/master/property_data.csv')

In [4]:
df.head(10)

PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000
1  100002000.0   197.0   LEXINGTON            N            3      1.5    --
2  100003000.0     NaN   LEXINGTON            N          NaN        1   850
3  100004000.0   201.0    BERKELEY           12            1      NaN   700
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0     NaN  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y           --        1   NaN
8  100009000.0   215.0     TREMONT            Y           na        2  1800

In [5]:
df['ST_NUM'].isnull()

0    False
1    False
2     True
3    False
4    False
5    False
6     True
7    False
8    False
Name: ST_NUM, dtype: bool

In [6]:
df.isnull().sum()

PID             1
ST_NUM          2
ST_NAME         0
OWN_OCCUPIED    1
NUM_BEDROOMS    2
NUM_BATH        1
SQ_FT           1
dtype: int64

In [7]:
df['NUM_BEDROOMS']

0      3
1      3
2    NaN
3      1
4      3
5    NaN
6      2
7     --
8     na
Name: NUM_BEDROOMS, dtype: object

In [8]:
df['NUM_BEDROOMS'].isnull()

0    False
1    False
2     True
3    False
4    False
5     True
6    False
7    False
8    False
Name: NUM_BEDROOMS, dtype: bool

In [11]:
missing_values = ["n/a", "na", "--"]

In [12]:
df['NUM_BEDROOMS']

0      3
1      3
2    NaN
3      1
4      3
5    NaN
6      2
7     --
8     na
Name: NUM_BEDROOMS, dtype: object

In [13]:
df['NUM_BEDROOMS'].isnull()

0    False
1    False
2     True
3    False
4    False
5     True
6    False
7    False
8    False
Name: NUM_BEDROOMS, dtype: bool

In [14]:
missing_values = ["n/a", "na", "--"]

In [17]:
df['OWN_OCCUPIED']

0      Y
1      N
2      N
3     12
4      Y
5      Y
6    NaN
7      Y
8      Y
Name: OWN_OCCUPIED, dtype: object

In [18]:
df['OWN_OCCUPIED'].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
Name: OWN_OCCUPIED, dtype: bool

In [19]:
cnt=0
for row in df['OWN_OCCUPIED']:
    try:
        int(row)
        df.loc[cnt, 'OWN_OCCUPIED']=np.nan
    except ValueError:
        pass
    cnt+=1

In [20]:
df.head(9)

PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000
1  100002000.0   197.0   LEXINGTON            N            3      1.5    --
2  100003000.0     NaN   LEXINGTON            N          NaN        1   850
3  100004000.0   201.0    BERKELEY          NaN            1      NaN   700
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0     NaN  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y           --        1   NaN
8  100009000.0   215.0     TREMONT            Y           na        2  1800

In [23]:
%matplotlib inline
data = pd.ExcelFile('C:\Users\hafit.jamaludin\Downloads\obes.xls')

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-23-7cf23abd7e97>, line 2)